[package]
name = "project_match"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.17.0"
glib = "0.17.5"
pangocairo = "0.17.0"
pango = "0.17.4"
gdk = "0.17.0"
